name: 'Terraform Workflow Template'

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version to use'
        required: false
        default: '1.5.0'
      working_directory:
        description: 'Directory containing Terraform configuration'
        required: false
        default: './terraform'
    secrets:
      AZURE_CREDENTIALS:
        description: 'Azure service principal credentials for authentication'
        required: true

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: 'Initialize Terraform'
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: 'Terraform Plan'
        working-directory: ${{ inputs.working_directory }}
        run: terraform plan

      - name: 'Terraform Apply'
        if: github.event_name == 'workflow_dispatch'
        working-directory: ${{ inputs.working_directory }}
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
