name: Manage Admin Team

on:
    workflow_dispatch:
    push:
        branches:
            - main
    

jobs:
  manage-admin-team:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Init gh cli
          run: gh auth login --with-token <<< ${{ secrets.SUPER_TOKEN }}

        - name: Get PR info
          uses: actions/github-script@v7
          id: get-pr
          with:
            script: |
                const pr = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    commit_sha: context.sha
                });
                const body = pr.data[0]?.body || '';
                const match = body.match(/<!--INPUTS([\s\S]*?)-->/);
                const inputs = match ? match[1].trim() : '';
                core.setOutput('inputs', inputs);

        - name: Use inputs
          run: echo "${{ steps.get-pr.outputs.inputs }}"


        - name: Add admin team
          run: |
            gh api -X PUT /orgs/${{ github.repository_owner }}/teams/admin/members
